name = "OpenQASM"
uuid = "a8821629-a4c0-4df7-9e00-12969ff383a7"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "2.0.1"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
RBNF = "83ef0002-5b9e-11e9-219b-65bac3c6d69c"

[compat]
MLStyle = "0.4"
RBNF = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
